# Generated by Django 5.2.5 on 2026-05-27 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler_api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="academic_year",
            field=models.CharField(
                choices=[
                    ("2nd Year", "2nd Year"),
                    ("3rd Year", "3rd Year"),
                    ("4th Year", "4th Year"),
                ],
                default="3rd Year",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="room_number",
            field=models.CharField(
                blank=True, default="Room 302", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="section",
            field=models.CharField(default="A", max_length=10),
        ),
        migrations.AddField(
            model_name="schedule",
            name="semester",
            field=models.IntegerField(choices=[(4, 4), (6, 6), (8, 8)], default=6),
        ),
        migrations.CreateModel(
            name="SwapRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Approved", "Approved"),
                            ("Rejected", "Rejected"),
                        ],
                        default="Pending",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requestor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_swap_requests",
                        to="scheduler_api.employee",
                    ),
                ),
                (
                    "schedule_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_requestor_slots",
                        to="scheduler_api.schedule",
                    ),
                ),
                (
                    "target_slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="swap_target_slots",
                        to="scheduler_api.schedule",
                    ),
                ),
                (
                    "target_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="received_swap_requests",
                        to="scheduler_api.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SyllabusLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("topic_covered", models.TextField()),
                (
                    "logged_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus_logs",
                        to="scheduler_api.employee",
                    ),
                ),
                (
                    "schedule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="syllabus_logs",
                        to="scheduler_api.schedule",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("HOD", "HOD"), ("Faculty", "Faculty")],
                        default="Faculty",
                        max_length=10,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "telegram_chat_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="user_profile",
                        to="scheduler_api.employee",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
