# Generated by Django 5.2.5 on 2026-05-28 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler_api", "0002_schedule_academic_year_schedule_room_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="department",
            field=models.CharField(default="CSE-AIDS", max_length=50),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="department",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
