# Generated by Django 5.2.5 on 2026-05-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scheduler_api", "0003_employee_department_userprofile_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="schedule",
            name="department",
            field=models.CharField(default="CSE-AIDS", max_length=50),
        ),
    ]
